{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "description": "Humidity in %",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 },
   "options": {
    "content": "# **WORKCENTER CONTROL DASHBOARD**"
   },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/conference_room\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "OUTSIDE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature in Celsius degrees",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/conference_room\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "description": "Temperature in Celsius degrees",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/conference_room\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "Humidity in %",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/conference_room\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "description": "Humidity in %",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/conference_room\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "LOBBY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature in Celsius degrees",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/lobby\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "Humidity in %",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/lobby\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Human presence",
   "type": "timeseries",
   "description": "0 is no human, 1 is human inside the room",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/lobby\")\n  |> filter(fn: (r) => r[\"_field\"] == \"presence\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "description": "0 is no light, 1 is lights on",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"light\")\n  |> filter(fn: (r) => r[\"topic\"] == \"office/lobby\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "OFFICE 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature in Celsius degrees",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/office1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "Humidity in %",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/office1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Human presence",
   "type": "timeseries",
   "description": "0 is no human, 1 is human inside the room",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/office1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"presence\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "description": "0 is no light, 1 is lights on",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"light\")\n  |> filter(fn: (r) => r[\"topic\"] == \"office/office1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "OFFICE 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature in Celsius degrees",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/office2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "Humidity in %",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/office2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Human presence",
   "type": "timeseries",
   "description": "0 is no human, 1 is human inside the room",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/office2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"presence\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "description": "0 is no light, 1 is lights on",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"light\")\n  |> filter(fn: (r) => r[\"topic\"] == \"office/office2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "CONFERENCE ROOM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperature in Celsius degrees",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/conference_room\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "Humidity in %",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/conference_room\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Human presence",
   "type": "timeseries",
   "description": "0 is no human, 1 is human inside the room",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"topic\"] == \"office/conference_room\")\n  |> filter(fn: (r) => r[\"_field\"] == \"presence\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "description": "0 is no light, 1 is lights on",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"iot_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"light\")\n  |> filter(fn: (r) => r[\"topic\"] == \"office/conference_room\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}